# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

body_attrs:
  class:"theme-base-09"

# Setup
title:            Christian Carrick
description:      
url:              carrickchristian.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
